# Generated by Django 3.2.18 on 2023-03-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_ambulance_subcounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='subcounty',
        ),
    ]
