# Generated by Django 3.2.18 on 2023-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_remove_ambulance_subcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
