# Generated by Django 3.2.18 on 2023-03-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_ambulance_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('decription', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='ambulance.sub_counties'),
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_phone', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TimeField()),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.emergencycartegory')),
            ],
        ),
    ]
