# Generated by Django 3.2.18 on 2023-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0005_auto_20230309_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TimeField(null=True),
        ),
    ]
