# Generated by Django 3.2.18 on 2023-03-09 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0006_alter_emergency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
