# Generated by Django 3.2.18 on 2023-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0007_emergency_reported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
