# Generated by Django 3.2.18 on 2023-03-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0010_alter_emergency_reported_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='contact_person_phone',
            new_name='contact_phone',
        ),
    ]
